### PR TITLE
Rebuild for proj 9.1.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Getting impatient waiting for the bot...

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@xylar but proj is not longer a requirement?!?

**Comment by xylar** [comment]
Oh, sorry, of course!

**Comment by xylar** [comment]
Thanks @akrherz

**Comment by dopplershift** [comment]
...but it probably should be? Only the imminent release of 0.21 removes the PROJ dependency in favor of just pyproj.

**Comment by xylar** [comment]
Yep, we merged that a couple of hours ago.

**Pull request closed without merging**
