### PR TITLE
cartopy v0.14.3

### PR DESCRIPTION
**Pull request by marqh**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@marqh do you know how to re-render with `conda-smithy`? That should fix the `AppVeyor` failure. If not I can do that later for you.

**Comment by marqh** [comment]
> do you know how to re-render with conda-smithy?

@ocefpaf i'm afraid I don't, but I'm happy to learn. Are there docs up? Or, is it an easy process to describe?

**Comment by ocefpaf** [comment]
- install conda-smithy: `conda install -c conda-forge conda-smithy` in your root env.
- type: `conda smithy rerender` at the root directory of the feedstock
- commit the changes.

PS: Another useful feature of `conda-smithy` is `conda smithy recipe-lint` to check lints of new recipes.

**Comment by marqh** [comment]
@ocefpaf I seem have have hit a few issues, such as:
```
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token

```

```
orig_npy = conda_build.config.config.CONDA_NPY
AttributeError: 'module' object has no attribute 'config'


```

so if you could fix this for me whilst I work out what might be going on, that'd be most helpful

thank you
mark

**Comment by ocefpaf** [comment]
> No circle token

That is should not be a problem. It is just a warning.

> AttributeError: 'module' object has no attribute 'config'

That may require a `conda`/`conda-build` update. Not sure...

**Comment by marqh** [comment]
hmmm....

i've updated conda and conda-build and I still get the same behaviour; puzzling

**Comment by ocefpaf** [comment]
What version of `conda-build-all` do you have there?

**Comment by marqh** [comment]
ocefpaf merged ....

thank you

**Comment by marqh** [comment]
> What version of conda-build-all do you have there?
```
conda-build-all           0.13.2                   py27_0    conda-forge
```

**Comment by ocefpaf** [comment]
> ocefpaf merged ....

:grimacing: See #18 (I too the easy path here :wink:)

**Comment by ocefpaf** [comment]
> conda-build-all           0.13.2                   py27_0    conda-forge

Latest is `1.0.0`. Maybe that is the culprit.

**Comment by marqh** [comment]
```
and put it in ~/.conda-smithy/anaconda.token
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........

CI support files regenerated. These need to be pushed to github!

You can commit the changes with:

    git add -A
    git commit -m 'MNT: Re-rendered with conda-smithy 1.3.3'


```

that does indeed seem to be it

many thanks

I assume that in this case there's no need to push to github, but next time ... ?

**Comment by ocefpaf** [comment]
> that does indeed seem to be it

Yep. That is it.

> I assume that in this case there's no need to push to github, but next time ... ?

`conda`, `conda-build`, `conda-build-all`, and `conda-smithy` have been such a moving target lately that I start my morning with an overral update before my coffee :smile:

**Pull request merged**
