### PR TITLE
backport natural earth download URL

### PR DESCRIPTION
**Pull request by akrherz**
Pull in patch from SciTools/cartopy#1833

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
Hmmm, rerendering brought in proj 8, which will not work.

**Comment by akrherz** [comment]
I am unsure what to do here.  I believe my patch is applying cleanly and at least Linux builds are happy.  The failures are unrelated to my patch it seems.

**Comment by zklaus** [comment]
@akrherz, it seems like you need another runtime package for windows. Try adding the following to the requirements/run section of the meta.yaml:
```
    - ucrt  # [win]
```

**Comment by akrherz** [comment]
> it seems like you need another runtime package for windows.

:pray: Thank you! CI is Green!  :rocket:

**Comment by xylar** [comment]
Thanks @akrherz and @zklaus!  I'll go ahead and merge this.

**Pull request merged**
