### PR TITLE
DO NOT MERGE. Working with the conda-smithy in development.

### PR DESCRIPTION
**Pull request by pelson**
Pairs up with https://github.com/conda-forge/conda-smithy/pull/193 so that we can see what it looks like (and that it still works).

### CODE REVIEW

**Comment by pelson** [comment]
I have updated to use @jakirkham's branch in https://github.com/conda-forge/conda-smithy/pull/196.

**Comment by pelson** [comment]
Curious that circle is green, yet I have the following in the log:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-forge-build-setup-2.2.0|                0           2 KB  conda-forge

The following NEW packages will be INSTALLED:

    conda-forge-build-setup: 2.2.0-0 conda-forge

Proceed ([y]/n)? Invalid choice: source run_conda_forge_build_setup
Proceed ([y]/n)? 
Fetching packages ...

```

**Comment by jakirkham** [comment]
Fixed in the PR to autoconfirm.

**Comment by pelson** [comment]
> Fixed in the PR to autoconfirm.

Thought you were going to sleep 😄

**Pull request closed without merging**
