### PR TITLE
Try manual Python 3.12 migration

### PR DESCRIPTION
**Pull request by djhoese**
Bot failed to do the migration according to conda-forge status and this is holding up CI for some of my projects. @conda-forge/cartopy or conda-forge admins, let me know if this is giong to make the migration bot mad.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by djhoese** [comment]
Note: This also assumes cartopy's last release is Python 3.12 compatible.

**Comment by djhoese** [comment]
Very confused by this failure on the Python 3.12 job:

```
Mamba failed to solve:
 - pip
 - libgcc-ng >=12
 - shapely >=1.7
 - libstdcxx-ng >=12
 - pyproj >=3.1.0
 - numpy >=1.26.0,<2.0a0
 - python >=3.12,<3.13.0a0
 - python >=3.12,<3.13.0a0 *_cpython
 - matplotlib-base >=3.4
 - pyshp >=2.1
 - python_abi 3.12.* *_cp312
 - packaging >=20

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package pyproj-3.2.1-py310h1a00971_5 requires python_abi 3.10.* *_cp310, but none of the providers can be installed

Leaving build/test directories:
  Work:
 /home/conda/feedstock_root/build_artifacts/work 
  Test:
 /home/conda/feedstock_root/build_artifacts/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/conda/feedstock_root/build_artifacts/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_ 
  Build:
source activate  /home/conda/feedstock_root/build_artifacts/_build_env 


Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 230, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 220, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - pip
 - libgcc-ng >=12
 - shapely >=1.7
 - libstdcxx-ng >=12
 - pyproj >=3.1.0
 - numpy >=1.26.0,<2.0a0
 - python >=3.12,<3.13.0a0
 - python >=3.12,<3.13.0a0 *_cpython
 - matplotlib-base >=3.4
 - pyshp >=2.1
 - python_abi 3.12.* *_cp312
 - packaging >=20

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package pyproj-3.2.1-py310h1a00971_5 requires python_abi 3.10.* *_cp310, but none of the providers can be installed

```

Oh or is this because pyproj doesn't build ppc64le packages?

**Comment by akrherz** [comment]
See conda-forge/pyproj-feedstock#144

**Comment by djhoese** [comment]
Yep, I just noticed that after I posted my last comment. Thanks @akrherz!

**Comment by ocefpaf** [comment]
BTW, I'm fine skipping ppc64le here. Afterall, pyproj doesn't really support it so it should not block the migration for all other archs just b/c one that is unsupported is failing.

**Comment by djhoese** [comment]
@conda-forge-admin restart ci

**Comment by djhoese** [comment]
@conda-forge-admin please rerender

**Comment by dopplershift** [comment]
@djhoese I think we need to rebuild pyproj first?

**Comment by dopplershift** [comment]
Just realized this will still be waiting on conda-forge/pyproj-feedstock#146.

**Comment by xylar** [comment]
> Just realized this will still be waiting on https://github.com/conda-forge/pyproj-feedstock/pull/146.

@dopplershift, I don't think so.  I think PyPy will be able to build from https://github.com/conda-forge/pyproj-feedstock/pull/143 and ppc64le from https://github.com/conda-forge/pyproj-feedstock/pull/144 so everyone should be covered, just not (yet) from the same build.

**Comment by dopplershift** [comment]
> > Just realized this will still be waiting on [conda-forge/pyproj-feedstock#146](https://github.com/conda-forge/pyproj-feedstock/pull/146).
> 
> @dopplershift, I don't think so. I think PyPy will be able to build from [conda-forge/pyproj-feedstock#143](https://github.com/conda-forge/pyproj-feedstock/pull/143) and ppc64le from [conda-forge/pyproj-feedstock#144](https://github.com/conda-forge/pyproj-feedstock/pull/144) so everyone should be covered, just not (yet) from the same build.

Yeah, I think that's right--that's why I cowardly deleted my comment. 😆

**Comment by djhoese** [comment]
And look at that, more CI failures. Yay!

**Comment by djhoese** [comment]
Maybe I created the migration wrong?

@conda-forge-admin please rerender

**Comment by xylar** [comment]
Given that OSX is affected, the move to clang 16 seems like the likely explanation.  I've been seeing that kind of thing elsewhere. 
 But the errors didn't make that completely obvious in this case.

**Comment by xylar** [comment]
The OSX error is:
```
Can't parse the binary at the index #1
   INFO: sysroot: '/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/' files: '['usr/share/man/mann/zero.n', 'usr/share/man/mann/yencode.n', 'usr/share/man/mann/yaml.n', 'usr/share/man/mann/xsxp.n']'
  ERROR (cartopy,lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so): Needed DSO lib/libc++.1.dylib found in ['libcxx']
  ERROR (cartopy,lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so): .. but ['libcxx'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
   INFO (cartopy,lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so): Needed DSO /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
WARNING (cartopy): run-exports library package conda-forge::numpy-1.22.4-py310hed37afb_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (cartopy): interpreted library (Python) package conda-forge::packaging-23.2-pyhd8ed1ab_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (cartopy): interpreter (Python) package conda-forge::python-3.10.12-had23ca6_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```
I'm not great with these kinds of error messages.  Is it complaining that C++ isn't needed?

**Comment by djhoese** [comment]
I read this as the opposite:

```
  ERROR (cartopy,lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so): Needed DSO lib/libc++.1.dylib found in ['libcxx']
  ERROR (cartopy,lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so): .. but ['libcxx'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```

"trace.so needs C++, but it isn't listed as a dependency"

I see "cxx" in the build dependencies, but not the run dependencies (`reqs/run`).

**Comment by djhoese** [comment]
And that module (trace.pyx) has loaded libcpp for 5 years so not sure why this is popping up now:

https://github.com/SciTools/cartopy/blame/74e02103e92d8fe8424c0937b71f7d768cb950c1/lib/cartopy/trace.pyx#L22-L23

I'll add cxx to the run deps and we'll see what happens. Ok?

**Comment by djhoese** [comment]
Another odd thing I noticed in the logs are these warnings which seem to be talking about 32-bit static libraries:

```
WARNING :: Failed to get_static_lib_exports(/Users/runner/miniforge3/conda-bld/cartopy_1698086232464/_build_env/lib/clang/16/lib/libclang_rt.cc_kext_i386_osx.a)
Unknown format
WARNING :: Failed to get_static_lib_exports(/Users/runner/miniforge3/conda-bld/cartopy_1698086232464/_build_env/lib/clang/16/lib/libclang_rt.builtins_i386_osx.a)
Unknown format
```

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Thanks for the hard work in getting this part of the tree rebuilt!

**Comment by djhoese** [comment]
So should the various bots/CIs figure out that this migration is complete for cartopy and update the status page and continue on down the dependency tree?

https://conda-forge.org/status/

I still see cartopy listed as "NOT-SOLVABLE".

**Comment by ocefpaf** [comment]
> I still see cartopy listed as "NOT-SOLVABLE".

It may take a while but let's ping @beckermr who probably knows better.

**Comment by djhoese** [comment]
FYI I just tried to rerun some CI in my projects and they don't seem to be able to get a compatible cartopy for Python 3.12. This is just ubuntu-latest in github actions.

```

  Looking for: ['cartopy', 'configobj', 'cython', 'dask', 'distributed', 'donfig', 'matplotlib', 'pillow', 'platformdirs', 'pyyaml', 'proj!=9.3.0', 'pyproj', 'pykdtree', 'rasterio', 'shapely', 'scipy', 'sphinx', 'toolz', 'xarray', 'zarr', 'coverage', 'pytest', 'pytest-cov', 'pytest-lazy-fixture', 'importlib-metadata', 'sphinx-reredirects', 'python=3.12']
  
  
  Could not solve for environment specs
  The following packages are incompatible
  ├─ cartopy   is installable with the potential options
  │  ├─ cartopy [0.15.1|0.16.0] would require
  │  │  └─ proj4 >=4.9.3,<4.9.4.0a0 , which can be installed;
  │  ├─ cartopy [0.13.1|0.14.0|...|0.17.0], which can be installed;
  │  ├─ cartopy [0.14.3|0.15.0|0.15.1] would require
  │  │  └─ geos 3.5.* , which does not exist (perhaps a missing channel);
  │  ├─ cartopy 0.15.1 would require
  │  │  └─ geos 3.5.1 , which does not exist (perhaps a missing channel);
  │  ├─ cartopy [0.16.0|0.17.0|0.18.0] would require
  │  │  └─ python >=3.7,<3.8.0a0  with the potential options
  │  │     ├─ python [3.7.0|3.7.1|...|3.7.9], which can be installed;
  │  │     └─ python [3.7.10|3.7.12|3.7.9] would require
  │  │        └─ python_abi 3.7 *_pypy37_pp73, which requires
  │  │           └─ python 3.7.* *_73_pypy, which conflicts with any installable versions previously reported;
  │  ├─ cartopy 0.17.0 would require
...
```

I've been looking at this stuff too long. Calling it a night and will look tomorrow.

**Comment by xylar** [comment]
@djhoese, conda-forge is currently pinning to `proj=9.3.0`:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L660-L661
This means all the newest packages that support python 3.12 and that require proj have been built with that version.  So you're going to have to figure out how to support `proj=9.3.0` if you want to use python 3.12.

**Comment by djhoese** [comment]
@xylar there was a bug in 9.3.0 that made our tests fail. I believe it was patched in the next release, but yeah good point. I suppose that pinning can't be changed to "9.3"? Probably some backwards incompatibility discovered between patch versions in the past.

**Comment by djhoese** [comment]
Ah you're right. It has just been fixed for so long that I assumed it was released already.

**Comment by djhoese** [comment]
Looks like the bot and status page have caught up. :tada:

**Pull request merged**
