### PR TITLE
build of 0.18.0b1

### PR DESCRIPTION
**Pull request by xylar**
This is just to make sure there aren't any unpleasant surprises,
see: https://github.com/SciTools/cartopy/issues/1458

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
The windows build errors must be related to this somehow:
https://github.com/SciTools/cartopy/blob/master/setup.py#L244-L247

I don't have a windows setup where I can investigate myself, but maybe the naming convention of the library has been changed back to be consistent with earlier versions of proj and other OSes.

**Comment by ocefpaf** [comment]
> The windows build errors must be related to this somehow:
> [SciTools/cartopy:setup.py@`master`#L244-L247](https://github.com/SciTools/cartopy/blob/master/setup.py#L244-L247) [](/SciTools/cartopy/blob/HEAD@{2020-02-11T07:33:38Z}/setup.py#L244-L247)
> 
> I don't have a windows setup where I can investigate myself, but maybe the naming convention of the library has been changed back to be consistent with earlier versions of proj and other OSes.


Indeed. Upstream renamed that to be just `proj.lib` instead of `proj_6_3.lib`. I have a PR for that. Let me test the patch here first before I upstream it.

**Comment by ocefpaf** [comment]
This passes! xref.: https://github.com/SciTools/cartopy/pull/1463

**Comment by dopplershift** [comment]
An option would be to actually put this on a separate label and go ahead and build/release the beta package.

**Comment by xylar** [comment]
@dopplershift, that seems useful to me.  @ocefpaf, how would I go about doing that?

**Comment by ocefpaf** [comment]
> @dopplershift, that seems useful to me. @ocefpaf, how would I go about doing that?

I changed the base from master to dev and updated the PR to [reflect cfep-05](https://github.com/conda-forge/cfep/blob/master/cfep-05.md). This should be OK to be merged to publish on the `cartopy_dev` label.

**Comment by xylar** [comment]
Looks good!  @ocefpaf, since I'm not a maintainer of this feedstock, I think you'll need to merge.

**Comment by xylar** [comment]
@ocefpaf, I just wanted to point someone to the conda package for `cartopy 0.18.0b1` and realized it never got created.  If you look here:
https://github.com/conda-forge/cartopy-feedstock/commits/dev
CI never ran on the merge commit.  Does the bot ignore the `dev` branch for some reason or did something else go wrong?

**Comment by ocefpaf** [comment]
> CI never ran on the merge commit.

:-(

> Does the bot ignore the dev branch for some reason or did something else go wrong?

It is not related to the bot. I'm investigating Azure logs to find out what happened.

**Comment by ocefpaf** [comment]
Looks like restarting the CIs did the trick:

https://anaconda.org/conda-forge/cartopy/files?channel=cartopy_dev

**Comment by xylar** [comment]
Great, glad you figured it out! Thanks!

**Pull request merged**
