### PR TITLE
Rebuild for python311

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by akrherz — APPROVED** [review]

**Comment by akrherz** [comment]
[matplotlib main builds failed](https://github.com/conda-forge/matplotlib-feedstock/runs/9170067634), digging more though.

**Comment by dopplershift** [comment]
The failures are a known issue with Matplotlib 3.6.1, and should be fixed by Matplotlib 3.6.2. Regardless, there's nothing wrong here, and the packages that are failing aren't even relevant to this rebuild.

**Comment by akrherz** [comment]
@dopplershift Is this the issue then? matplotlib/matplotlib#24094

**Comment by dopplershift** [comment]
Yes, and conda-forge/matplotlib-feedstock#332.

**Comment by ocefpaf** [comment]
Wow! We are in cartopy already! This migration may be the first one to end in a few months instead of +1 year!

**Pull request merged**
