### PR TITLE
Don't skip Python 3.5

### PR DESCRIPTION
**Pull request by ocefpaf**
The only thing that worries me is that I could not get geos to compile on Windows and Python 3.5 using features. See https://github.com/conda-forge/geos-feedstock/pull/5#issuecomment-201940475

### CODE REVIEW

**Comment by pelson** [comment]
> The only thing that worries me is that I could not get geos to compile on Windows and Python 3.5 using features

I'd say that if there is a problem downstream, the feedstock should be able to deal with that automatically - there should be no annotation in this recipe about which dependencies exist IMO.

**Comment by ocefpaf** [comment]
I could not get `conda smithy rerender` to add the `CONDA_PY: 35`lines. Should I just add them manually or do you want to investigate?

**Comment by pelson** [comment]
>> I'd say that if there is a problem downstream, the feedstock should be able to deal with that automatically - there should be no annotation in this recipe about which dependencies exist IMO.

> I could not get conda smithy rerender to add the CONDA_PY: 35lines. Should I just add them manually or do you want to investigate?

Hehe. That is precisely what is going on here. We can't *build* cartopy against py35 because it doesn't have all of its dependencies available - so there was no matrix item in the CI. The **recipe** shouldn't reflect that, but the feedstock certainly could (and does).

**Comment by pelson** [comment]
Let's merge and see how we get on. :+1:

**Comment by ocefpaf** [comment]
Ah OK. I though that the removal of skip alone would update the CI config.

BTW which dependency is missing? We do have a "generic" geos that is working. The failure I comment above is in a PR that tries to use features to compile geos.

**Comment by pelson** [comment]
> The failure I comment above is in a PR that tries to use features to compile geos.

I see. In which case, I'm uncertain. I'm not too worried, but I can dig further if you want. Searching with ```conda search -c conda-forge --platform win-64 <dep name>``` is one option. Ideally we'd have a tool to diagnose these.

**Comment by ocefpaf** [comment]
I think I found the problem: https://github.com/conda-forge/cartopy-feedstock/blob/master/recipe/meta.yaml#L19

**Comment by dopplershift** [comment]
So what's the status on building for Python 3.5? I think the packages on anaconda.org cause Python 3.5rc4 to be installed.

**Comment by ocefpaf** [comment]
OS X and Linux packages for Python 3.5 are already in the channel. Windows will be soon. (See #5.)

**Comment by dopplershift** [comment]
Right, but if I ask to install CartoPy in Python 3.5.1 I get:

```
Fetching package metadata: ..........
Solving package specifications: ....
Error: The following specifications were found to be in conflict:
  - cartopy -> numpy 1.8*
  - cartopy -> python 2.7*|3.4*|>=2.7,<3.5
  - python 3.5.1*
Use "conda info <package>" to see the dependencies for each package.
```

Asking for info on the package:
```
cartopy 0.14.0 np110py35_0
--------------------------
file name   : cartopy-0.14.0-np110py35_0.tar.bz2
name        : cartopy
version     : 0.14.0
build number: 0
build string: np110py35_0
channel     : conda-forge
size        : 1.6 MB
arch        : x86_64
binstar     : {'owner_id': '5528f42ce1dad12974506e8d', 'channel': 'main', 'package_id': '56f0128969180359233aa1e4'}
license     : GNU LGPL
machine     : x86_64
md5         : cd174eff02418251034aed6d1933e3c8
operatingsystem: darwin
platform    : osx
subdir      : osx-64
target-triplet: x86_64-any-darwin
installed environments:
dependencies:
    matplotlib
    mock
    nose
    numpy 1.10*
    owslib
    pillow
    proj.4
    pyepsg
    pyshp
    python 3.5*
    python >=2.7,<3.5
    scipy
    shapely >=1.5.6
    six
```
So the 3.5 package depends on `python 3.5*` and `python <3.5`, which results in requiring python 3.5.0rc4; that's not good.

**Comment by ocefpaf** [comment]
Ah. That should be fixed in #5 too. I did not notice that the binaries were affected by that.

**Comment by dopplershift** [comment]
Somehow I missed #5, thanks!

**Pull request merged**
